### ISSUE TITLE
PHPUnit reports error

### ISSUE THREAD

**Issue by nitro2010-zz** [justinhunt/moodle-assignsubmission_youtube#2]
assignsubmission_youtube

 1) core_test_generator_testcase::test_create_module
Declaration of assign_submission_youtube::get_files() should be compatible with assign_plugin::get_files(stdClass $submissionorgrade, stdClass $user)
/home/travis/build/nitro2010/moodle-testing/mod/assign/submission/youtube/locallib.php:715
/home/travis/build/nitro2010/moodle-testing/mod/assign/locallib.php:345
/home/travis/build/nitro2010/moodle-testing/mod/assign/locallib.php:345
/home/travis/build/nitro2010/moodle-testing/mod/assign/locallib.php:157
/home/travis/build/nitro2010/moodle-testing/mod/assign/lib.php:40
/home/travis/build/nitro2010/moodle-testing/course/modlib.php:122
/home/travis/build/nitro2010/moodle-testing/lib/testing/generator/module_generator.php:263
/home/travis/build/nitro2010/moodle-testing/mod/assign/tests/generator/lib.php:59
/home/travis/build/nitro2010/moodle-testing/lib/testing/generator/data_generator.php:441
/home/travis/build/nitro2010/moodle-testing/lib/testing/tests/generator_test.php:203
/home/travis/build/nitro2010/moodle-testing/lib/phpunit/classes/advanced_testcase.php:80
To re-run:
 vendor/bin/phpunit core_test_generator_testcase lib/testing/tests/generator_test.php
FAILURES!
Tests: 24, Assertions: 240, Errors: 1.

**Comment by justinhunt** [comment]
This looks a bit familiar to something I had to do on another assignment submission type last year. Can you confirm this is a problem or not (I see you closed it). Thanks.

**Comment by nitro2010-zz** [comment]
Hello Justin,

I send you message by PoodLL website that you have old version in Moodle directory.
I updated this plugin and PHPUnit no report any errors.

regards.
